### ISSUE TITLE
Hazmat Armor & Rubber

### ISSUE THREAD

**Issue by dani31c** [LightStudio6/LightStudio-Update#1]
Currently the hazmat armor has no recipe or it doesnt show on JEI, which is kind of suspicious to me.

So if it had no one, maybe adding rubber as a material for new stuff and for crafting the hazmat armor?

**Comment by LightStudio6** [comment]
We are currently working on your suggestion

**Comment by LightStudio6** [comment]
Problem fixed in the last update 1.12 (https://www.curseforge.com/minecraft/mc-mods/lightstrudio-update/files/3427174)

**Comment by dani31c** [comment]
This is just a question, how can I obtain rubber.

**Comment by LightStudio6** [comment]
To get rubber, you have to put a slimeball in a furnace
