### ISSUE TITLE
Unpermitted redistribution of assets

### ISSUE THREAD

**Issue by Su5eD** [LightStudio6/LightStudio-Update#3]
As seen of the images on CurseForge, this mod contains multiple textures from Thermal Series, Immersive Engineering, Pam's Harvestcraft, Mekanism, Iron Chests, and maybe several other mods.

The mod is licensed as All Rights Reverved, therefore claiming all textures as yours and violating their licenses.
You are advised to remove these textures from your mod, otherwise action might be taken by their authors.

Disclaimer: I am not acting on behalf of any of the mentioned mods' authors. This is only **general advice**.

See also: [Proprietary Software is Often Malware](https://www.gnu.org/proprietary/proprietary.html)

**Comment by LightStudio6** [comment]
All texture are all MIT Licence except one or two assets

**Comment by LightStudio6** [comment]
After this problem bothers you, you do not have to download it.

**Comment by Su5eD** [comment]
> After this problem bothers you, you do not have to download it.

I am not the one who should be bothered here :)

Also, MIT **requires** you to preserve the license and copyright notice, which I can't find on the mod page.

**Comment by LightStudio6** [comment]
Sorry but I don't take care of the site, only the issue part, I send the problem to the people concerned
